/* FLAIR MASTER CONFIG | auto-generated at 2017-12-01T11:35:10-0800 (ISO-8601) */
flair.load__by_id = function () {
	for (var key in flair.names) {
		if (flair.names.hasOwnProperty(key)) {
			var data = key.split(' ');

			var orig_id = data[2];

			if (orig_id.substring(0, 'a'.length) === 'a') {
				orig_id = orig_id.substring(1);
			}
			if (orig_id.substring(orig_id.length - 'm'.length) === 'm') {
				orig_id = orig_id.substring(0, orig_id.length - 1);
			}
			if (orig_id.substring(orig_id.length - 'o'.length) === 'o') {
				orig_id = orig_id.substring(0, orig_id.length - 1);
			}
			if (orig_id.substring(orig_id.length - 'x'.length) === 'x') {
				orig_id = orig_id.substring(0, orig_id.length - 1);
			}
			if (orig_id.substring(orig_id.length - 'y'.length) === 'y') {
				orig_id = orig_id.substring(0, orig_id.length - 1);
			}
			if (orig_id.substring(orig_id.length - 1).match(/[a-z]/i) &&
				orig_id.substring(0, orig_id.length - 1).match(/^\d+$/)) {
				orig_id = orig_id.substring(0, orig_id.length - 1);
			}

			var flair_class = '';
			for (var i = 0; i < data.length; i++) {
				flair_class += 'flair-' + data[i] + ' ';
			}

			flair_class = flair_class.slice(0, -1);


			flair.by_id[data[2]] = {
				key: key,
				heropos: data[0],
				sheet: data[1],
				hero_id: data[2],
				orig_id: orig_id,
				hero_name: flair.names[key],
				flair_class: flair_class,
			}
		}
	}
};
flair.by_id = {};
flair.names = {
	/* [STANDARD] */





"AbsorbingMan00 character absorbingman" : "Absorbing Man [Modern] #Super Villain# #Villain# #Combat# #Male# #Human# #Strong#",
"AdamWarlock00 character adam" : "Adam Warlock [Modern] #Super Hero# #Hero# #Blast# #Male# #Creature# #Time Freezing Immunity# #Magic#",
"Agent1300 character sharon" : "Agent 13 [Modern] #Super Hero# #Hero# #Speed# #Female# #Human# #Agent#",
"Agent1301 uniform sharon1" : "Agent 13 [Captain America: Civil War] #Super Hero# #Hero# #Speed# #Female# #Human# #MCU# #Agent#",
"AgentVenom00 character agentvenom" : "Agent Venom [All-New, All-Different] #Super Hero# #Hero# #Combat# #Male# #Human# #Symbiote# #Leadership# #Agent# #Potential#",
"AgentVenom01 uniform agentvenom1" : "Agent Venom [Agent Anti-Venom] #Super Hero# #Hero# #Combat# #Male# #Human# #Symbiote# #Leadership# #Agent# #Potential#",
"AmericaChavez00 character america" : "America Chavez [Ultimates] #Super Hero# #Hero# #Combat# #Female# #Human# #Fast Movement# #Strong#",
"AncientOne00 character ancient" : "Ancient One [Modern] #Super Hero# #Hero# #Blast# #Male# #Human# #Leadership# #Magic# #Support#",
"AncientOne01 uniform ancient1" : "Ancient One [Marvel's Doctor Strange] #Super Hero# #Hero# #Blast# #Female# #Human# #MCU# #Leadership# #Magic# #Support#",
"Angel00 character angel" : "Angel [Classic] #Super Hero# #Hero# #Speed# #Male# #Mutant# #X-Men# #Leadership# #Fast Movement# #Support# #Potential#",
"Angel01 uniform angel1" : "Archangel [X-Force] #Super Hero# #Hero# #Speed# #Male# #Mutant# #X-Force# #Leadership# #Fast Movement# #Support# #Potential#",
"Angela00 character angela" : "Angela [Modern] #Super Hero# #Hero# #Universal# #Female# #Alien# #Weapons Master#",
"Angela01 uniform angela1" : "Angela [Secret Wars: 1602 Witch Hunter Angela] #Super Hero# #Hero# #Universal# #Female# #Alien# #Weapons Master#",
"Angela02 uniform angela2" : "Angela [All-New, All-Different] #Super Hero# #Hero# #Universal# #Female# #Alien# #Weapons Master#",
"AntiMan00 character antiman" : "Anti-Man [All-New, All-Different] #Super Villain# #Villain# #Universal# #Male# #Human# #Energy Projection# #Fast Movement#",
"Antman00 character ant" : "Ant-Man [Modern] #Super Hero# #Hero# #Speed# #Male# #Human# #Agility# #Potential# #Tier3#",
"Antman01 uniform ant1" : "Ant-Man [Marvel's Ant-Man] #Super Hero# #Hero# #Speed# #Male# #Human# #MCU# #Agility# #Potential# #Tier3#",
"Antman02 uniform ant2" : "Ant-Man [Captain America: Civil War] #Super Hero# #Hero# #Speed# #Male# #Human# #MCU# #Agility# #Potential# #Tier3#",
"Antman03 uniform ant3" : "Ant-Man [Marvel's Ant-Man and the Wasp] #Super Hero# #Hero# #Speed# #Male# #Human# #MCU# #Agility# #Potential# #Tier3#",
"Antman04 uniform ant4" : "Ant-Man [Marvel's Avengers: Endgame] #Super Hero# #Hero# #Speed# #Male# #Human# #MCU# #Avengers# #Agility# #Potential# #Tier3# #New#",
"Antman05 uniform ant5" : "Ant-Man [Team Suit] #Super Hero# #Hero# #Speed# #Male# #Human# #MCU# #Avengers# #Agility# #Potential# #Tier3# #New#",
"Apocalypse00 character apocalypse" : "Apocalypse [Age of Apocalypse] #Super Villain# #Villain# #Combat# #Male# #Mutant# #Durability# #Fast Movement# #Pure Evil#",
"Arachknight00 character arachknight" : "Arachknight [Infinity Warps] #Super Hero# #Hero# #Speed# #Male# #Human# #Leadership# #Weapons Master# #Spider-Sense# #Potential#",
"BaronMordo00 character mordo" : "Baron Mordo [Classic] #Super Villain# #Villain# #Blast# #Male# #Human# #Pure Evil# #Magic#",
"BaronMordo01 uniform mordo1" : "Mordo [Marvel's Doctor Strange] #Super Villain# #Villain# #Speed# #Male# #Human# #MCU# #Heightened Senses# #Agility#",
"Beast00 character beast" : "Beast [Classic] #Super Hero# #Hero# #Combat# #Male# #Mutant# #X-Men# #Agility# #Strong# #Support#",
"Beast01 uniform beast1" : "Beast [Age of Apocalypse] #Super Villain# #Villain# #Combat# #Male# #Mutant# #Agility# #Strong# #Support#",
"BlackBolt00 character bolt" : "Black Bolt [Modern] #Super Hero# #Hero#  #Universal# #Male# #Inhuman# #Energy Projection# #Fast Movement#",
"BlackBolt01 uniform bolt1" : "Black Bolt [All-New, All-Different] #Super Hero# #Hero#  #Universal# #Male# #Inhuman# #Energy Projection# #Fast Movement#",
"BlackBolt02 uniform bolt2" : "Black Bolt [Inhumans: Attilan Rising] #Super Hero# #Hero#  #Universal# #Male# #Inhuman# #Energy Projection# #Fast Movement#",
"BlackCat00 character cat" : "Black Cat [Modern] #Super Villain# #Villain# #Speed# #Female# #Human# #Agility#",
"BlackCat01 uniform cat1" : "Black Cat [Claws] #Super Villain# #Villain# #Speed# #Female# #Human# #Agility#",
"BlackCat02 uniform cat2" : "Black Cat [All-New, All-Different] #Super Villain# #Villain# #Speed# #Female# #Human# #Agility#",
"BlackDwarf00 character dwarf" : "Black Dwarf [Infinity] #Super Villain# #Villain# #Universal# #Male# #Alien# #Black Order# #Durability# #Strong# #Potential#",
"BlackDwarf01 uniform dwarf1" : "Cull Obsidian [Marvel's Avengers: Infinity War] #Super Villain# #Villain# #Universal# #Male# #Human# #MCU# #Black Order# #Durability# #Strong# #Potential#",
"BlackPanther00 character panther" : "Black Panther [Modern] #Super Hero# #Hero# #Combat# #Male# #Human# #Command# #Agility# #Potential# #Tier3#",
"BlackPanther01 uniform panther1" : "Black Panther [Captain America: Civil War] #Super Hero# #Hero# #Combat# #Male# #Human# #MCU# #Command# #Agility# #Potential# #Tier3#",
"BlackPanther02 uniform panther2" : "Black Panther [Marvel's Black Panther] #Super Hero# #Hero# #Combat# #Male# #Human# #MCU# #Command# #Agility# #Potential# #Tier3#",
"BlackWidow00 character widow" : "Black Widow [The Avengers] #Super Hero# #Hero# #Speed# #Female# #Human# #MCU# #Avengers# #Agent# #Agility# #Potential#",
"BlackWidow01 uniform widow1" : "Black Widow [Avengers: Age of Ultron] #Super Hero# #Hero# #Speed# #Female# #Human# #MCU# #Avengers# #Agent# #Agility# #Potential#",
"BlackWidow02 uniform widow2" : "Black Widow [Secret Wars: 2099] #Super Hero# #Hero# #Speed# #Female# #Human# #Avengers# #Agent# #Agility# #Potential#",
"BlackWidow03 uniform widow3" : "Black Widow [Captain America: Civil War] #Super Hero# #Hero# #Speed# #Female# #Human# #MCU# #Avengers# #Agent# #Agility# #Potential#",
"BlackWidow04 uniform widow4" : "Black Widow [Marvel's Avengers: Infinity War] #Super Hero# #Hero# #Speed# #Female# #Human# #MCU# #Avengers# #Agent# #Agility# #Potential#",
"BlackWidow05 uniform widow5" : "Black Widow [Marvel's Avengers: Endgame] #Super Hero# #Hero# #Speed# #Female# #Human# #MCU# #Avengers# #Agent# #Agility# #Potential# #New#",
"BlackWidow06 uniform widow6" : "Black Widow [Team Suit] #Super Hero# #Hero# #Speed# #Female# #Human# #MCU# #Avengers# #Agent# #Agility# #Potential# #New#",
"Blade00 character blade" : "Blade [Modern] #Super Hero# #Hero# #Combat# #Male# #Human# #Weapons Master# #Healing#",
"Blade01 uniform blade1" : "Blade [70's Classic] #Super Hero# #Hero# #Combat# #Male# #Human# #Weapons Master# #Healing#",
"BlueMarvel00 character bluemarvel" : "Blue Marvel [Ultimates] #Super Hero# #Hero# #Universal# #Male# #Human# #Energy Projection# #Leadership#",
"Bullseye00 character bullseye" : "Bullseye [Modern] #Super Villain# #Villain# #Combat# #Male# #Human# #Pure Evil# #Weapons Master#",
"Bullseye01 uniform bullseye1" : "Bullseye [Secret Wars: 1872] #Super Villain# #Villain# #Combat# #Male# #Human# #Pure Evil# #Weapons Master#",
"Cable00 character cable" : "Cable [Modern] #Super Hero# #Hero# #Blast# #Male# #Mutant# #Leadership# #Weapons Master# #Potential#",
"Cable01 uniform cable1" : "Cable [X-Force] #Super Hero# #Hero# #Blast# #Male# #Mutant# #X-Force# #Leadership# #Weapons Master# #Potential#",
"CaptainAmerica00 character cap" : "Captain America [The Avengers] #Super Hero# #Hero# #Combat# #Male# #Human# #MCU# #Avengers# #Command# #Leadership# #Potential# #Tier3#",
"CaptainAmerica01 uniform cap1" : "Captain America [Avengers: Age of Ultron] #Super Hero# #Hero# #Combat# #Male# #Human# #MCU# #Avengers# #Command# #Leadership# #Potential# #Tier3#",
"CaptainAmerica02 uniform cap2" : "Captain America [Secret Wars: 2099] #Super Hero# #Hero# #Combat# #Female# #Human# #Command# #Leadership# #Potential# #Tier3#",
"CaptainAmerica03 uniform cap3" : "Captain America [Captain America: The Winter Soldier] #Super Hero# #Hero# #Combat# #Male# #Human# #MCU# #Avengers# #Command# #Leadership# #Potential# #Tier3#",
"CaptainAmerica04 uniform cap4" : "Captain America [Captain America: Civil War] #Super Hero# #Hero# #Combat# #Male# #Human# #MCU# #Avengers# #Command# #Leadership# #Potential# #Tier3#",
"CaptainAmerica05 uniform cap5" : "Captain America [Marvel NOW!] #Super Hero# #Hero# #Combat# #Male# #Human# #Command# #Leadership# #Potential# #Tier3#",
"CaptainAmerica06 uniform cap6" : "Captain America [Marvel's Avengers: Infinity War] #Super Hero# #Hero# #Combat# #Male# #Human# #MCU# #Avengers# #Command# #Leadership# #Potential# #Tier3#",
"CaptainAmerica07 uniform cap7" : "Captain America [Marvel's Avengers: Endgame] #Super Hero# #Hero# #Combat# #Male# #Human# #MCU# #Avengers# #Command# #Leadership# #Potential# #Tier3# #New#",
"CaptainAmerica08 uniform cap8" : "Captain America [Team Suit] #Super Hero# #Hero# #Combat# #Male# #Human# #MCU# #Avengers# #Command# #Leadership# #Potential# #Tier3# #New#",
"CaptainAmericaSharonRogers00 character sharonrogers" : "Captain America (Sharon Rogers) [Captain America 75th Anniversary] #Super Hero# #Hero# #Blast# #Female# #Human# #Original# #Energy Projection# #Leadership# #Potential# #Tier3#",
"CaptainAmericaSharonRogers01 uniform sharonrogers1" : "Captain America (Sharon Rogers) [Starlight Armor] #Super Hero# #Hero# #Blast# #Female# #Human# #Original# #Energy Projection# #Leadership# #Potential# #Tier3#",
"CaptainAmericaSharonRogers02 uniform sharonrogers2" : "Captain America (Sharon Rogers) [Dark Star Armor] #Super Hero# #Hero# #Blast# #Female# #Human# #Original# #Energy Projection# #Leadership# #Potential# #Tier3#",
"CaptainMarvel00 character danvers" : "Captain Marvel [Modern] #Super Hero# #Hero# #Universal# #Female# #Human# #Energy Projection# #Fast Movement# #Leadership#",
"CaptainMarvel01 uniform danvers1" : "Captain Marvel [Secret Wars: Captain Marvel & The Carol Corps] #Super Hero# #Hero# #Universal# #Female# #Human# #Energy Projection# #Fast Movement# #Leadership#",
"CaptainMarvel02 uniform danvers2" : "Captain Marvel [Ms. Marvel] #Super Hero# #Hero# #Universal# #Female# #Human# #Energy Projection# #Fast Movement# #Leadership#",
"CaptainMarvel03 uniform danvers3" : "Captain Marvel [Captain Marvel] #Super Hero# #Hero# #Universal# #Female# #Human# #MCU# #Energy Projection# #Fast Movement# #Leadership# #Potential# #Tier3#",
"Carnage00 character carnage" : "Carnage [All-New, All-Different] #Super Villain# #Villain# #Combat# #Male# #Human# #Pure Evil# #Healing# #Symbiote# #Support#",
"Clea00 character clea" : "Clea [Modern] #Super Hero# #Hero# #Universal# #Female# #Alien# #Fast Movement# #Magic#",
"Colossus00 character colossus" : "Colossus [Modern] #Super Hero# #Hero# #Combat# #Male# #Mutant# #X-Men# #Leadership# #Strong# #Support# #Potential#",
"Colossus01 uniform colossus1" : "Colossus [X-Force] #Super Hero# #Hero# #Combat# #Male# #Mutant# #X-Force# #Leadership# #Strong# #Support# #Potential#",
"CorvusGlaive00 character corvus" : "Corvus Glaive [Infinity] #Super Villain# #Villain# #Universal# #Male# #Alien# #Black Order# #Fast Movement# #Agility# #Potential#",
"CorvusGlaive01 uniform corvus1" : "Corvus Glaive [Marvel's Avengers: Infinity War] #Super Villain# #Villain# #Universal# #Male# #Alien# #MCU# #Black Order# #Fast Movement# #Agility# #Potential#",
"Crescent00 character crescent" : "Crescent [Modern] #Super Hero# #Hero# #Combat# #Female# #Human# #Original# #Strong# #Durability# #Leadership# #Potential#",
"Crossbones00 character crossbones" : "Crossbones [Captain America: Civil War] #Super Villain# #Villain# #Combat# #Male# #Human# #MCU# #Weapons Master#",
"Crossbones01 uniform crossbones1" : "Crossbones [Modern] #Super Villain# #Villain# #Combat# #Male# #Human# #Weapons Master#",
"Crystal00 character crystal" : "Crystal [All-New, All-Different] #Super Hero# #Hero#  #Blast# #Female# #Inhuman# #Energy Projection# #Command# #Potential#",
"Crystal01 uniform crystal1" : "Crystal [Royal Suit] #Super Hero# #Hero#  #Blast# #Female# #Inhuman# #Energy Projection# #Command# #Potential#",
"Crystal02 uniform crystal2" : "Crystal [Fantastic Four] #Super Hero# #Hero#  #Blast# #Female# #Inhuman# #Fantastic Four# #Energy Projection# #Command# #Potential#",
"Cyclops00 character cyclops" : "Cyclops [Classic] #Super Hero# #Hero# #Blast# #Male# #Mutant# #X-Men# #Command# #Energy Projection# #Support#",
"Cyclops01 uniform cyclops1" : "Cyclops [Age of Apocalypse] #Super Villain# #Villain# #Blast# #Male# #Mutant# #Command# #Energy Projection# #Support#",
"Cyclops02 uniform cyclops2" : "Cyclops [Marvel NOW!] #Super Hero# #Hero# #Blast# #Male# #Mutant# #X-Men# #Command# #Energy Projection# #Support#",
"DaisyJohnson00 character daisy" : "Daisy Johnson [Marvel's Agents of S.H.I.E.L.D.] #Super Hero# #Hero# #Blast# #Female# #Inhuman# #MCU# #Shield# #Agent# #Mind Resist# #Support#",
"DaisyJohnson01 uniform daisy1" : "Quake [Modern] #Super Hero# #Hero# #Blast# #Female# #Inhuman# #Shield# #Agent# #Mind Resist# #Support#",
"DaisyJohnson02 uniform daisy2" : "Daisy Johnson [Marvel's Agents of S.H.I.E.L.D. (Quake] #Super Hero# #Hero# #Blast# #Female# #Inhuman# #MCU# #Shield# #Agent# #Mind Resist# #Support#",
"Daredevil00 character devil" : "Daredevil [Modern] #Super Hero# #Hero# #Speed# #Male# #Human# #Defenders# #Leadership# #Heightened Senses# #Agility#",
"Daredevil01 uniform devil1" : "Daredevil [Devil of Hell's Kitchen] #Super Hero# #Hero# #Speed# #Male# #Human# #MCU# #Defenders# #Leadership# #Heightened Senses# #Agility#",
"Daredevil02 uniform devil2" : "Daredevil [All-New, All-Different] #Super Hero# #Hero# #Speed# #Male# #Human# #Defenders# #Leadership# #Heightened Senses# #Agility#",
"Deadpool00 character deadpool" : "Deadpool [Modern] #Super Hero# #Hero# #Speed# #Male# #Mutant# #Healing# #Weapons Master# #Potential# #Tier3#",
"Deadpool01 uniform deadpool1" : "Deadpool [X-Force] #Super Hero# #Hero# #Speed# #Male# #Mutant# #X-Force# #Healing# #Weapons Master# #Potential# #Tier3#",
"Deathlok00 character deathlok" : "Deathlok [Marvel's Agents of S.H.I.E.L.D.] #Super Hero# #Hero# #Combat# #Male# #Human# #MCU# #Shield# #Agent# #Machine#",
"Deathlok01 uniform deathlok1" : "Deathlok [Modern] #Super Hero# #Hero# #Blast# #Male# #Human# #Shield# #Agent# #Machine#",
"Destroyer00 character destroyer" : "Destroyer [Classic] #Neutral# #Universal# #Genderless# #Creature# #Asgard# #Flame#",
"Destroyer01 uniform destroyer1" : "Destroyer [Prometheus] #Neutral# #Universal# #Genderless# #Creature# #Asgard# #Flame#",
"DoctorDoom00 character doom" : "Doctor Doom [Modern] #Super Villain# #Villain# #Universal# #Male# #Human# #Magic# #Pure Evil# #Potential#",
"DoctorOctopus00 character ock" : "Doctor Octopus [Classic] #Super Villain# #Villain# #Combat# #Male# #Human# #Sinister Six# #Durability# #Machine#",
"DoctorOctopus01 uniform ock1" : "Doctor Octopus [Superior Spider-Man] #Super Hero# #Hero# #Combat# #Male# #Human# #Spidey# #Agility# #Machine# #Spider-Sense#",
"DoctorStrange00 character strange" : "Doctor Strange [All-New, All-Different] #Super Hero# #Hero# #Blast# #Male# #Human# #Fast Movement# #Magic# #Potential#",
"DoctorStrange01 uniform strange1" : "Doctor Strange [Marvel's Doctor Strange] #Super Hero# #Hero# #Blast# #Male# #Human# #MCU# #Fast Movement# #Magic# #Potential#",
"DoctorStrange02 uniform strange2" : "Doctor Strange [Marvel's Avengers: Infinity War] #Super Hero# #Hero# #Blast# #Male# #Human# #MCU# #Avengers# #Fast Movement# #Magic# #Potential#",
"Domino00 character domino" : "Domino [X-Force] #Super Hero# #Hero# #Speed# #Female# #Mutant# #X-Force# #Weapons Master# #Agility# #Potential#",
"Dormammu00 character dormammu" : "Dormammu [Classic] #Super Villain# #Villain# #Universal# #Male# #Alien# #Pure Evil# #Magic#",
"Drax00 character drax" : "Drax [Guardians of the Galaxy] #Super Hero# #Hero# #Combat# #Male# #Alien# #MCU# #Guardians# #Healing#",
"Drax01 uniform drax1" : "Drax [All-New, All-Different] #Super Hero# #Hero# #Combat# #Male# #Alien# #Guardians# #Healing#",
"EbonyMaw00 character maw" : "Ebony Maw [Infinity] #Super Villain# #Villain# #Universal# #Male# #Alien# #Black Order# #Fast Movement# #Mind Resist# #Pure Evil# #Potential#",
"EbonyMaw01 uniform maw1" : "Ebony Maw [Marvel's Avengers: Infinity War] #Super Villain# #Villain# #Universal# #Male# #Alien# #MCU# #Black Order# #Fast Movement# #Mind Resist# #Pure Evil# #Support# #Potential#",
"Elektra00 character elektra" : "Elektra [Classic] #Super Hero# #Hero# #Speed# #Female# #Human# #Weapons Master#",
"Elektra01 uniform elektra1" : "Elektra [Marvel's Daredevil] #Super Hero# #Hero# #Speed# #Female# #Human# #MCU# #Defenders# #Weapons Master#",
"ElsaBloodstone00 character elsa" : "Elsa Bloodstone [Modern] #Super Hero# #Hero# #Speed# #Female# #Human# #Weapons Master#",
"ElsaBloodstone01 uniform elsa1" : "Elsa Bloodstone [Secret Wars: Marvel Zombies] #Super Hero# #Hero# #Speed# #Female# #Human# #Weapons Master#",
"ElsaBloodstone02 uniform elsa2" : "Elsa Bloodstone [Monsters Unleashed! (MFF Variant)] #Super Hero# #Hero# #Speed# #Female# #Human# #Weapons Master#",
"EmmaFrost00 character emma" : "Emma Frost [Modern] #Super Hero# #Hero# #Blast# #Female# #Mutant# #Durability# #Mind Resist# #Potential#",
"EmmaFrost01 uniform emma1" : "Emma Frost [Marvel NOW!] #Super Hero# #Hero# #Blast# #Female# #Mutant# #Durability# #Mind Resist# #Potential#",
"Enchantress00 character enchantress" : "Enchantress [Modern] #Super Villain# #Villain# #Blast# #Female# #Alien# #Asgard# #Mind# #Magic#",
"Falcon00 character falcon" : "Falcon [Captain America: The Winter Soldier] #Super Hero# #Hero# #Speed# #Male# #Human# #MCU# #Avengers# #Leadership# #Fast Movement#",
"Falcon01 uniform falcon1" : "Falcon [All-New Captain America] #Super Hero# #Hero# #Speed# #Male# #Human# #Avengers# #Leadership# #Fast Movement#",
"Falcon02 uniform falcon2" : "Falcon [Captain America: Civil War] #Super Hero# #Hero# #Speed# #Male# #Human# #MCU# #Avengers# #Leadership# #Fast Movement#",
"Falcon03 uniform falcon3" : "Falcon [Marvel Legacy] #Super Hero# #Hero# #Speed# #Male# #Human# #Avengers# #Leadership# #Fast Movement#",
"Fandral00 character fandral" : "Fandral [Modern] #Super Hero# #Hero# #Speed# #Male# #Alien# #Asgard# #Agility#",
"Fantomex00 character fantomex" : "Fantomex [X-Force] #Super Hero# #Hero# #Speed# #Male# #Mutant# #X-Force# #Weapons Master# #Agility# #Potential#",
"Fenris00 character fenris" : "Fenris Wolf [Fenris Wolf] #Super Villain# #Villain# #Genderless# #Alien# #Asgard# #NPC#",
"FrostBeast00 character frostbeast" : "Frost Beast [Frost Beast] #Super Villain# #Villain# #Genderless# #Alien# #Asgard# #NPC#",
"Gambit00 character gambit" : "Gambit [Modern] #Super Hero# #Hero# #Blast# #Male# #Mutant# #X-Men# #Mind# #Agility# #Potential#",
"Gamora00 character gamora" : "Gamora [Guardians of the Galaxy] #Super Hero# #Hero# #Speed# #Female# #Alien# #MCU# #Guardians# #Agility# #Weapons Master#",
"Gamora01 uniform gamora1" : "Gamora [All-New, All-Different] #Super Hero# #Hero# #Speed# #Female# #Alien# #Guardians# #Agility# #Weapons Master#",
"Gamora02 uniform gamora2" : "Gamora [Guardians of the Galaxy 2] #Super Hero# #Hero# #Speed# #Female# #Alien# #MCU# #Guardians# #Agility# #Weapons Master#",
"Ghost00 character ghost" : "Ghost [Modern] #Super Villain# #Villain# #Speed# #Male# #Human# #Machine# #Weapons Master# #Potential#",
"Ghost01 uniform ghost1" : "Ghost [Marvel's Ant-Man and the Wasp] #Super Villain# #Villain# #Speed# #Female# #Human# #MCU# #Machine# #Weapons Master# #Support# #Potential#",
"GhostPanther00 character ghostpanther" : "Ghost Panther [Infinity Warps] #Super Hero# #Hero# #Universal# #Male# #Human# #Flame# #Agility# #Support# #Potential#",
"GhostRider00 character rider" : "Ghost Rider [Classic] #Super Hero# #Hero# #Universal# #Male# #Human# #Flame# #Leadership#",
"GhostRider01 uniform rider1" : "Ghost Rider [70's Classic] #Super Hero# #Hero# #Universal# #Male# #Human# #Flame# #Leadership#",
"GhostRider02 uniform rider2" : "Ghost Rider [Inhumans: Attilan Rising] #Super Hero# #Hero# #Universal# #Male# #Human# #Flame# #Leadership#",
"GhostRiderRobbieReyes00 character robbie" : "Ghost Rider (Robbie Reyes) [Marvel NOW!] #Super Hero# #Hero# #Universal# #Male# #Human# #Flame# #Fast Movement#",
"GiantMan00 character giant" : "Giant-Man [Modern] #Super Hero# #Hero# #Combat# #Male# #Human# #Strong# #Potential#",
"GiantMan01 uniform giant1" : "Goliath [Modern] #Super Hero# #Hero# #Combat# #Male# #Human# #Strong# #Potential#",
"GiantMan02 uniform giant2" : "Giant-Man [Ultron Pym] #Super Villain# #Villain# #Universal# #Male# #Human# #Strong# #Potential#",
"Goliath00 character goliath" : "Goliath [Classic] #Super Hero# #Hero# #Combat# #Male# #Human# #Durability# #Strong#",
"Gorgon00 character gorgon" : "Gorgon [War of Kings] #Super Hero# #Hero#  #Combat# #Male# #Inhuman# #Strong#",
"GreenGoblin00 character goblin" : "Green Goblin [Classic] #Super Villain# #Villain# #Speed# #Male# #Human# #Sinister Six# #Fast Movement# #Poison#",
"GreenGoblin01 uniform goblin1" : "Green Goblin [Ultimate] #Super Villain# #Villain# #Combat# #Male# #Human# #Sinister Six# #Fast Movement# #Flame#",
"Groot00 character groot" : "Groot [Guardians of the Galaxy] #Super Hero# #Hero# #Combat# #Male# #Alien# #MCU# #Guardians# #Healing# #Support# #Potential#",
"Groot01 uniform groot1" : "Groot [Secret Wars: Thors] #Super Hero# #Hero# #Universal# #Male# #Alien# #Guardians# #Healing# #Support# #Potential#",
"Groot02 uniform groot2" : "Groot [Guardians of the Galaxy 2] #Super Hero# #Hero# #Speed# #Male# #Alien# #MCU# #Guardians# #Healing# #Support# #Potential#",
"Groot03 uniform groot3" : "Groot [Marvel's Avengers: Infinity War] #Super Hero# #Hero# #Combat# #Male# #Alien# #MCU# #Avengers# #-# #Guardians# #Healing# #Support# #Potential#",
"Gwenpool00 character gwenpool" : "Gwenpool [All-New, All-Different] #Super Hero# #Hero# #Speed# #Female# #Human# #Agility#",
"Gwenpool01 uniform gwenpool1" : "Gwenpool [Gwen Poole] #Super Hero# #Hero# #Speed# #Female# #Human# #Agility#",
"Hawkeye00 character hawkeye" : "Hawkeye [The Avengers] #Super Hero# #Hero# #Speed# #Male# #Human# #MCU# #Avengers# #Agent# #Weapons Master#",
"Hawkeye01 uniform hawkeye1" : "Hawkeye [Avengers: Age of Ultron] #Super Hero# #Hero# #Speed# #Male# #Human# #MCU# #Avengers# #Agent# #Weapons Master#",
"Hawkeye02 uniform hawkeye2" : "Hawkeye [Captain America: Civil War] #Super Hero# #Hero# #Speed# #Male# #Human# #MCU# #Avengers# #Agent# #Weapons Master#",
"Hawkeye03 uniform hawkeye3" : "Hawkeye [Classic] #Super Hero# #Hero# #Speed# #Male# #Human# #Avengers# #Agent# #Weapons Master#",
"Hawkeye04 uniform hawkeye4" : "Ronin [Marvel's Avengers: Endgame] #Super Hero# #Hero# #Speed# #Male# #Human# #MCU# #Avengers# #Agent# #Weapons Master# #Potential# #New#",
"HawkeyeKateBishop00 character kate" : "Hawkeye (Kate Bishop) [Marvel NOW!] #Super Hero# #Hero# #Speed# #Female# #Human# #Agent# #Agility#",
"Heimdall00 character heimdall" : "Heimdall [Marvel's Thor: Ragnarok] #Super Hero# #Hero# #Universal# #Male# #Alien# #MCU# #Asgard# #Strong#",
"Hela00 character hela" : "Hela [Modern] #Super Villain# #Villain# #Universal# #Female# #Alien# #Asgard# #Pure Evil# #Command#",
"Hela01 uniform hela1" : "Hela [Marvel's Thor: Ragnarok] #Super Villain# #Villain# #Universal# #Female# #Alien# #MCU# #Asgard# #Pure Evil# #Command# #Support#",
"Hellcat00 character hellcat" : "Hellcat [All-New, All-Different] #Super Hero# #Hero# #Speed# #Female# #Human# #Defenders# #Agility#",
"Hellstorm00 character daimon" : "Hellstorm [Modern] #Super Hero# #Hero# #Universal# #Male# #Human# #Flame# #Magic#",
"Hogun00 character hogun" : "Hogun [Modern] #Super Hero# #Hero# #Combat# #Male# #Alien# #Asgard# #Strong#",
"Hulk00 character hulk" : "Hulk [The Avengers] #Super Hero# #Hero# #Combat# #Male# #Human# #Avengers# #Durability# #Strong# #Potential#",
"Hulk01 uniform hulk1" : "Hulk [Secret Wars: Future Imperfect] #Super Hero# #Hero# #Combat# #Male# #Human# #Durability# #Strong# #Potential#",
"Hulk02 uniform hulk2" : "Hulk [World War Hulk] #Super Hero# #Hero# #Combat# #Male# #Human# #Durability# #Strong# #Potential#",
"Hulk03 uniform hulk3" : "Hulk [Marvel's Thor: Ragnarok] #Super Hero# #Hero# #Combat# #Male# #Human# #MCU# #Avengers# #Durability# #Strong# #Potential#",
"Hulk04 uniform hulk4" : "Hulk [Marvel's Avengers: Endgame] #Super Hero# #Hero# #Combat# #Male# #Human# #MCU# #Avengers# #Durability# #Strong# #Potential# #New#",
"Hulk05 uniform hulk5" : "Hulk [Team Suit] #Super Hero# #Hero# #Combat# #Male# #Human# #MCU# #Avengers# #Durability# #Strong# #Potential# #New#",
"HulkAmadeusCho00 character cho" : "Hulk (Amadeus Cho) [Totally Awesome Hulk] #Super Hero# #Hero# #Combat# #Male# #Human# #Durability# #Strong#",
"HulkAmadeusCho01 uniform cho1" : "Hulk (Amadeus Cho) [Monsters Unleashed! (MFF Variant)] #Super Hero# #Hero# #Combat# #Male# #Human# #Durability# #Strong#",
"Hulkbuster00 character hb" : "Hulkbuster (Iron Mark Mark 44) [Avengers: Age of Ultron] #Super Hero# #Hero# #Combat# #Male# #Creature# #MCU# #Avengers# #Machine# #Strong#",
"Hulkbuster01 uniform hb1" : "Hulkbuster (Iron Mark Mark 43) [Heavy Duty Armor] #Super Hero# #Hero# #Combat# #Male# #Creature# #Avengers# #Machine# #Strong#",
"Hulkbuster02 uniform hb2" : "Hulkbuster 2.0 [Marvel's Avengers: Infinity War] #Super Hero# #Hero# #Combat# #Male# #Creature# #MCU# #Avengers# #Machine# #Strong#",
"Hulkling00 character hulkling" : "Hulkling [New Avengers] #Super Hero# #Hero# #Combat# #Male# #Alien# #Durability# #Strong#",
"HumanTorch00 character torch" : "Human Torch [Modern] #Super Hero# #Hero# #Blast# #Male# #Human# #Fantastic Four# #Fast Movement# #Flame# #Potential#",
"Hyperion00 character hyperion" : "Hyperion [All-New, All-Different] #Super Hero# #Hero# #Universal# #Male# #Alien# #Energy Projection# #Leadership# #Potential#",
"Hyperion01 uniform hyperion1" : "Hyperion [Classic] #Super Hero# #Hero# #Universal# #Male# #Alien# #Energy Projection# #Leadership# #Potential#",
"Inferno00 character inferno" : "Inferno [All-New, All-Different] #Super Hero# #Hero#  #Blast# #Male# #Inhuman# #Flame#",
"Inferno01 uniform inferno1" : "Inferno [Modern] #Super Hero# #Hero#  #Blast# #Male# #Inhuman# #Flame#",
"InvisibleWoman00 character sue" : "Invisible Woman [Modern] #Super Hero# #Hero#  #Blast# #Female# #Human# #Fantastic Four# #Energy Projection# #Potential#",
"IronFist00 character fist" : "Iron Fist [Classic] #Super Hero# #Hero# #Combat# #Male# #Human# #Defenders# #Healing# #Agility#",
"IronFist01 uniform fist1" : "Iron Fist [New Avengers] #Super Hero# #Hero# #Combat# #Male# #Human# #Defenders# #Healing# #Agility#",
"IronFist02 uniform fist2" : "Iron Fist [All-New, All-Different] #Super Hero# #Hero# #Combat# #Male# #Human# #Defenders# #Healing# #Agility#",
"IronFist03 uniform fist3" : "Iron Fist [Marvel's Iron Fist] #Super Hero# #Hero# #Combat# #Male# #Human# #MCU# #Defenders# #Healing# #Agility#",
"IronHammer00 character ironhammer" : "Iron Hammer [Infinity Warps] #Super Hero# #Hero# #Universal# #Male# #Alien# #Magic# #Shock# #Machine# #Potential#",
"Ironheart00 character ironheart" : "Ironheart [Marvel NOW!] #Super Hero# #Hero# #Blast# #Female# #Human# #Leadership# #Machine#",
"IronMan00 character im" : "Iron Man [The Avengers] #Super Hero# #Hero# #Blast# #Male# #Human# #MCU# #Avengers# #Energy Projection# #Machine# #Potential# #Tier3#",
"IronMan01 uniform im1" : "Iron Man [Avengers: Age of Ultron] #Super Hero# #Hero# #Blast# #Male# #Human# #MCU# #Avengers# #Energy Projection# #Machine# #Potential# #Tier3#",
"IronMan02 uniform im2" : "Iron Man [Secret Wars: 2099] #Super Hero# #Hero# #Blast# #Male# #Human# #Energy Projection# #Machine# #Potential# #Tier3#",
"IronMan03 uniform im3" : "Iron Man [Captain America: Civil War] #Super Hero# #Hero# #Blast# #Male# #Human# #MCU# #Avengers# #Energy Projection# #Machine# #Potential# #Tier3#",
"IronMan04 uniform im4" : "Iron Man [Marvel's Avengers: Infinity War] #Super Hero# #Hero# #Blast# #Male# #Human# #MCU# #Avengers# #Energy Projection# #Machine# #Potential# #Tier3#",
"IronMan05 uniform im5" : "Iron Man [Marvel's Avengers: Endgame] #Super Hero# #Hero# #Blast# #Male# #Human# #MCU# #Avengers# #Energy Projection# #Machine# #Potential# #Tier3# #New#",
"IronMan06 uniform im6" : "Iron Man [Team Suit] #Super Hero# #Hero# #Blast# #Male# #Human# #MCU# #Avengers# #Energy Projection# #Machine# #Potential# #Tier3# #New#",
"JeanGrey00 character jean" : "Jean Grey [Phoenix] #Super Hero# #Hero# #Blast# #Female# #Mutant# #X-Men# #Phoenix Force# #Mind# #Mind Resist#",
"JessicaJones00 character jessica" : "Jessica Jones [Modern] #Super Hero# #Hero# #Combat# #Female# #Human# #MCU# #Defenders# #Durability# #Strong#",
"Jocasta00 character jocasta" : "Jocasta [Jocasta] #Super Hero# #Hero# #Female# #Creature# #NPC#",
"Juggernaut00 character juggernaut" : "Juggernaut [Brotherhood of Mutants] #Super Villain# #Villain# #Combat# #Male# #Mutant# #Brotherhood# #Strong# #Durability# #Pure Evil# #Potential#",
"Kaecilius00 character kaecilius" : "Kaecilius [Marvel's Doctor Strange] #Super Villain# #Villain# #Blast# #Male# #Human# #MCU# #Agility# #Magic#",
"Karnak00 character karnak" : "Karnak [War of Kings] #Super Hero# #Hero#  #Speed# #Male# #Inhuman# #Heightened Senses#",
"Karnak01 uniform karnak1" : "Karnak [All-New, All-Different] #Super Hero# #Hero#  #Speed# #Male# #Inhuman# #Heightened Senses#",
"KidKaiju00 character kaiju" : "Kid Kaiju [Monsters Unleashed!] #Super Hero# #Hero# #Speed# #Male# #Inhuman# #Command# #Support#",
"KidKaiju01 uniform kaiju1" : "Kid Kaiju [Monsters Unleashed! (MFF Variant)] #Super Hero# #Hero# #Speed# #Male# #Inhuman# #Command# #Support#",
"Killmonger00 character killmonger" : "Killmonger [Classic] #Super Villain# #Villain# #Combat# #Male# #Human# #Command# #Strong#",
"Killmonger01 uniform killmonger1" : "Erik Killmonger [Black Panther] #Super Villain# #Villain# #Combat# #Male# #Human# #MCU# #Command# #Strong#",
"Kingpin00 character kingpin" : "Kingpin [Modern] #Super Villain# #Villain# #Combat# #Male# #Human# #Command# #Strong#",
"Kingpin01 uniform kingpin1" : "Kingpin [Secret Wars: Armor Wars] #Super Villain# #Villain# #Blast# #Male# #Human# #Command# #Strong# #Machine#",
"Korath00 character korath" : "Korath [Captain Marvel] #Super Villain# #Villain# #Speed# #Male# #Alien# #MCU# #Pure Evil# #Weapons Master# #Potential#",
"KravenTheHunter00 character kraven" : "Kraven The Hunter [Modern] #Super Villain# #Villain# #Speed# #Male# #Human# #Sinister Six# #Agility# #Weapons Master#",
"Lash00 character lash" : "Lash [Marvel's Agents of S.H.I.E.L.D.] #Super Villain# #Villain#  #Blast# #Male# #Inhuman# #MCU# #Shield# #Energy Projection#",
"Lash01 uniform lash1" : "Lash [Modern] #Super Villain# #Villain#  #Blast# #Male# #Inhuman# #Energy Projection#",
"Lincoln00 character lincoln" : "Lincoln [Marvel's Agents of S.H.I.E.L.D.] #Super Hero# #Hero#  #Blast# #Male# #Inhuman# #MCU# #Shield# #Shock#",
"Lizard00 character lizard" : "Lizard [Classic] #Super Villain# #Villain# #Combat# #Male# #Human# #Sinister Six# #Healing#",
"Loki00 character loki" : "Loki [The Avengers] #Super Villain# #Villain# #Universal# #Male# #Alien# #MCU# #Asgard# #Chill# #Mind#",
"Loki01 uniform loki1" : "Loki [Lady Loki] #Super Villain# #Villain# #Universal# #Female# #Alien# #Asgard# #Chill# #Mind#",
"Loki02 uniform loki2" : "Loki [Marvel's Thor: Ragnarok] #Super Villain# #Villain# #Universal# #Male# #Alien# #MCU# #Asgard# #Chill# #Mind#",
"Loki03 uniform loki3" : "Loki [Classic] #Super Villain# #Villain# #Universal# #Male# #Alien# #Asgard# #Chill# #Mind#",
"LukeCage00 character luke" : "Luke Cage [Modern] #Super Hero# #Hero# #Combat# #Male# #Human# #Defenders# #Durability# #Strong#",
"LukeCage01 uniform luke1" : "Luke Cage [All-New, All-Different] #Super Hero# #Hero# #Combat# #Male# #Human# #Defenders# #Durability# #Strong#",
"LukeCage02 uniform luke2" : "Luke Cage [Marvel's Luke Cage] #Super Hero# #Hero# #Combat# #Male# #Human# #MCU# #Defenders# #Durability# #Strong#",
"LunaSnow00 character luna" : "Luna Snow [Modern] #Super Hero# #Hero# #Speed# #Female# #Human# #Cold Blooded# #Leadership# #Support# #Potential# #Tier3#",
"LunaSnow01 uniform luna1" : "Luna Snow [Andromeda Suit] #Super Hero# #Hero# #Speed# #Female# #Human# #Cold Blooded# #Leadership# #Support# #Potential# #Tier3#",
"M.O.D.O.K.00 character modok" : "M.O.D.O.K. [Classic] #Super Villain# #Villain# #Blast# #Male# #Human# #Pure Evil# #Machine# #Mind#",
"M.O.D.O.K.01 uniform modok1" : "M.O.D.O.K. [SPIDOC] #Super Villain# #Villain# #Blast# #Male# #Human# #Spidey# #Pure Evil# #Machine# #Mind#",
"M.O.D.O.K.02 uniform modok2" : "M.O.D.O.K. [CAPDOC] #Super Villain# #Villain# #Blast# #Male# #Human# #Pure Evil# #Machine# #Mind#",
"Magik00 character magik" : "Magik [Modern] #Super Hero# #Hero# #Blast# #Female# #Mutant# #X-Men# #Magic# #Mind Resist#",
"Magneto00 character magneto" : "Magneto [Classic] #Super Villain# #Villain# #Blast# #Male# #Mutant# #Brotherhood# #Mind Resist# #Energy Projection #Potential# #Tier3#",
"Magneto01 uniform magneto1" : "Magneto [Marvel NOW!] #Super Villain# #Villain# #Blast# #Male# #Mutant# #Brotherhood# #Mind Resist# #Energy Projection #Potential# #Tier3#",
"Malekith00 character malekith" : "Malekith [Thor: The Dark World] #Super Villain# #Villain# #Blast# #Male# #Alien# #MCU# #Asgard# #Pure Evil#",
"Malekith01 uniform malekith1" : "Malekith [All-New, All-Different] #Super Villain# #Villain# #Blast# #Male# #Alien# #Asgard# #Pure Evil#",
"Mantis00 character mantis" : "Mantis [Guardians of the Galaxy 2] #Super Hero# #Hero# #Blast# #Female# #Alien# #MCU# #Guardians# #Healing# #Mind# #Support#",
"Maximus00 character maximus" : "Maximus [War of Kings] #Super Villain# #Villain#  #Blast# #Male# #Inhuman# #Pure Evil# #Mind Resist#",
"MBaku00 character mbaku" : "M'Baku [Marvel's Black Panther] #Super Villain# #Villain# #Male# #Human# #NPC#",
"Medusa00 character medusa" : "Medusa [All-New, All-Different] #Super Hero# #Hero#  #Universal# #Female# #Inhuman# #Command# #Potential#",
"Medusa01 uniform medusa1" : "Medusa [Monsters Unleashed! (MFF Variant)] #Super Hero# #Hero#  #Universal# #Female# #Inhuman# #Command# #Potential#",
"MidgardSerpent00 character midgardserpent" : "Midgard Serpent [Midgard Serpent] #Super Villain# #Villain# #Neutral# #Alien# #Asgard# #NPC#",
"Minn-Erva00 character erva" : "Minn-Erva [Modern] #Super Villain# #Villain# #Combat# #Female# #Alien# #Pure Evil# #Durability# #Strong# #Potential#",
"Minn-Erva01 uniform erva1" : "Minn-Erva [Captain Marvel] #Super Villain# #Villain# #Combat# #Female# #Alien# #MCU# #Pure Evil# #Durability# #Strong# #Potential#",
"MistyKnight00 character misty" : "Misty Knight [All-New, All-Different] #Super Hero# #Hero# #Speed# #Female# #Human# #Defenders# #Weapons Master# #Agent#",
"MisterFantastic00 character reed" : "Mister Fantastic [Modern] #Super Hero# #Hero# #Combat# #Male# #Human# #Fantastic Four# #Durability# #Leadership# #Potential# #Tier3#",
"Mockingbird00 character mockingbird" : "Mockingbird [Heroic Age] #Super Hero# #Hero# #Speed# #Female# #Human# #Shield# #Agent# #Agility#",
"Mockingbird01 uniform mockingbird1" : "Bobbi Morse [Marvel's Agents of S.H.I.E.L.D.] #Super Hero# #Hero# #Speed# #Female# #Human# #MCU# #Shield# #Agent# #Agility#",
"Mockingbird02 uniform mockingbird2" : "Mockingbird [All-New, All-Different] #Super Hero# #Hero# #Speed# #Female# #Human# #Shield# #Agent# #Agility#",
"MoonGirl00 character moongirl" : "Moon Girl [Marvel NOW!] #Super Hero# #Hero#  #Blast# #Female# #Inhuman# #Leadership# #Weapons Master# #Potential#",
"MoonGirl01 uniform moongirl1" : "Moon Girl [Monsters Unleashed!] #Super Hero# #Hero#  #Blast# #Female# #Inhuman# #Leadership# #Weapons Master# #Potential#",
"MoonKnight00 character moonknight" : "Moon Knight [Modern] #Super Hero# #Hero# #Combat# #Male# #Human# #Leadership# #Weapons Master#",
"MoonKnight01 uniform moonknight1" : "Moon Knight [Armored] #Super Hero# #Hero# #Combat# #Male# #Human# #Leadership# #Weapons Master#",
"MorganLeFay00 character morgan" : "Morgan Le Fay [Modern] #Super Villain# #Villain# #Universal# #Female# #Human# #Pure Evil# #Magic# #Potential#",
"MsMarvelKamalaKhan00 character kamala" : "Ms. Marvel (Kamala Khan) [All-New, All-Different] #Super Hero# #Hero# #Combat# #Female# #Inhuman# #Healing# #Strong#",
"MsMarvelKamalaKhan01 uniform kamala1" : "Ms. Marvel (Kamala Khan) [Karachi Costume] #Super Hero# #Hero# #Speed# #Female# #Inhuman# #Healing# #Strong#",
"Mysterio00 character mysterio" : "Mysterio [Classic] #Super Villain# #Villain# #Blast# #Male# #Human# #Sinister Six# #Mind#",
"Nebula00 character nebula" : "Nebula [Guardians of the Galaxy] #Super Villain# #Villain# #Combat# #Female# #Alien# #MCU# #Guardians# #Weapons Master# #Shock# #Potential#",
"Nebula01 uniform nebula1" : "Nebula [Classic] #Super Villain# #Villain# #Combat# #Female# #Alien# #Weapons Master# #Shock# #Potential#",
"Nebula02 uniform nebula2" : "Nebula [Marvel's Avengers: Endgame] #Super Hero# #Hero# #Combat# #Female# #Alien# #Avengers# #-# #Guardians# #Weapons Master# #Shock# #Potential# #New#",
"Nebula03 uniform nebula3" : "Nebula [Team Suit] #Super Hero# #Hero# #Combat# #Female# #Alien# #Avengers# #-# #Guardians# #Weapons Master# #Shock# #Potential# #New#",
"NickFury00 character fury" : "Nick Fury [Modern] #Super Hero# #Hero# #Speed# #Male# #Human# #Shield# #Weapons Master# #Leadership# #Agent# #Support#",
"NickFury01 uniform fury1" : "Nick Fury [Captain America] #Super Hero# #Hero# #Speed# #Male# #Human# #MCU# #Shield# #Weapons Master# #Leadership# #Agent# #Support# #Potential#",
"Nightcrawler00 character nightcrawler" : "Nightcrawler [Modern] #Super Hero# #Hero# #Speed# #Male# #Mutant# #X-Men# #Leadership# #Agility# #Potential#",
"Nightcrawler01 uniform nightcrawler1" : "Nightcrawler [X-Force] #Super Hero# #Hero# #Speed# #Male# #Mutant# #X-Force# #Leadership# #Agility# #Potential#",
"NovaSamAlexander00 character samalexander" : "Nova (Sam Alexander) [All-New, All-Different] #Super Hero# #Hero# #Universal# #Male# #Human# #Energy Projection# #Fast Movement#",
"Odin00 character odin" : "Odin [Modern] #Super Hero# #Hero# #Universal# #Male# #Alien# #Asgard# #Energy Projection# #Command# #Support#",
"PhilCoulson00 character coulson" : "Phil Coulson [Marvel's Agents of S.H.I.E.L.D.] #Super Hero# #Hero# #Blast# #Male# #Human# #MCU# #Shield# #Agent# #Command# #Support#",
"PhilCoulson01 uniform coulson1" : "Phil Coulson [A.O.S. Season 3] #Super Hero# #Hero# #Blast# #Male# #Human# #MCU# #Shield# #Agent# #Command# #Support#",
"ProximaMidnight00 character proxima" : "Proxima Midnight [Infinity] #Super Villain# #Villain# #Universal# #Female# #Alien# #Black Order# #Fast Movement# #Agility#",
"ProximaMidnight01 uniform proxima1" : "Proxima Midnight [Marvel's Avengers: Infinity War] #Super Villain# #Villain# #Universal# #Female# #Alien# #MCU# #Black Order# #Fast Movement# #Agility#",
"Psylocke00 character psylocke" : "Psylocke [X-Force] #Super Hero# #Hero# #Blast# #Female# #Mutant# #X-Force# #Mind# #Agility# #Potential#",
"Punisher00 character punisher" : "Punisher [Modern] #Super Hero# #Hero# #Combat# #Male# #Human# #Defenders# #Weapons Master# #Leadership#",
"Punisher01 uniform punisher1" : "Punisher [Noir] #Super Hero# #Hero# #Combat# #Male# #Human# #Defenders# #Weapons Master# #Leadership#",
"Punisher02 uniform punisher2" : "Punisher [War Journal] #Super Hero# #Hero# #Combat# #Male# #Human# #Defenders# #Weapons Master# #Leadership#",
"Punisher03 uniform punisher3" : "Punisher [Marvel's Daredevil] #Super Hero# #Hero# #Combat# #Male# #Human# #MCU# #Defenders# #Weapons Master# #Leadership#",
"Punisher04 uniform punisher4" : "Punisher [Marvel Legacy] #Super Hero# #Hero# #Combat# #Male# #Human# #Defenders# #Leadership# #Weapons Master# #Machine#",
"QuasarAvrilKincaid00 character avril" : "Quasar (Avril Kincaid) [All-New, All-Different] #Super Hero# #Hero# #Universal# #Female# #Human# #Energy Projection# #Heightened Senses#",
"Quicksilver00 character quicksilver" : "Quicksilver [Classic] #Super Hero# #Hero# #Speed# #Male# #Other# #Agility# #Fast Movement#",
"Quicksilver01 uniform quicksilver1" : "Quicksilver [Marvel Legacy] #Super Hero# #Hero# #Speed# #Male# #Other# #Agility# #Fast Movement#",
"RedHulk00 character rulk" : "Red Hulk [Modern] #Super Villain# #Villain# #Combat# #Male# #Human# #Flame# #Durability#",
"RedHulk01 uniform rulk1" : "Red Hulk [Marvel NOW!] #Super Hero# #Hero# #Combat# #Male# #Human# #Flame# #Durability#",
"RedSkull00 character skull" : "Red Skull [Captain America: The First Avenger] #Super Villain# #Villain# #Blast# #Male# #Human# #MCU# #Command# #Pure Evil#",
"RedSkull01 uniform skull1" : "Red Skull [Secret Wars: Red Skull] #Super Villain# #Villain# #Speed# #Male# #Human# #Command# #Pure Evil#",
"Rhino00 character rhino" : "Rhino [Classic] #Super Villain# #Villain# #Combat# #Male# #Human# #Sinister Six# #Durability# #Strong#",
"RocketRaccoon00 character rocket" : "Rocket Raccoon [Guardians of the Galaxy] #Super Hero# #Hero# #Blast# #Male# #Alien# #MCU# #Guardians# #Weapons Master# #Potential#",
"RocketRaccoon01 uniform rocket1" : "Rocket Raccoon [All-New, All-Different] #Super Hero# #Hero# #Blast# #Male# #Alien# #Guardians# #Weapons Master# #Potential#",
"RocketRaccoon02 uniform rocket2" : "Rocket Raccoon [Guardians of the Galaxy 2] #Super Hero# #Hero# #Blast# #Male# #Alien# #MCU# #Guardians# #Weapons Master# #Potential#",
"RocketRaccoon03 uniform rocket3" : "Rocket Raccoon [Marvel's Avengers: Infinity War] #Super Hero# #Hero# #Blast# #Male# #Alien# #MCU# #Avengers# #-# #Guardians# #Weapons Master# #Potential#",
"RocketRaccoon04 uniform rocket4" : "Rocket Raccoon [Marvel's Avengers: Endgame] #Super Hero# #Hero# #Blast# #Male# #Alien# #MCU# #Avengers# #-# #Guardians# #Weapons Master# #Potential# #New#",
"RocketRaccoon05 uniform rocket5" : "Rocket Raccoon [Team Suit] #Super Hero# #Hero# #Blast# #Male# #Alien# #MCU# #Avengers# #-# #Guardians# #Weapons Master# #Potential# #New#",
"Rogue00 character rogue" : "Rogue [Classic] #Super Hero# #Hero# #Speed# #Female# #Mutant# #X-Men# #Fast Movement# #Healing#",
"Rogue01 uniform rogue1" : "Rogue [Age of Apocalypse] #Super Hero# #Hero# #Speed# #Female# #Mutant# #X-Men# #Fast Movement# #Healing#",
"Ronan00 character ronan" : "Ronan [Guardians of the Galaxy] #Super Villain# #Villain# #Universal# #Male# #Alien# #MCU# #Guardians# #Command# #Mind Resist# #Support#",
"Ronan01 uniform ronan1" : "Ronan [Annihilation] #Super Villain# #Villain# #Universal# #Male# #Alien# #Guardians# #Command# #Mind Resist# #Support#",
"Ronan02 uniform ronan2" : "Ronan [Captain Marvel] #Super Villain# #Villain# #Universal# #Male# #Alien# #MCU# #Guardians# #Command# #Mind Resist# #Support# #Potential#",
"Sabretooth00 character sabretooth" : "Sabretooth [Brotherhood of Mutants] #Super Villain# #Villain# #Combat# #Male# #Mutant# #Brotherhood# #Pure Evil# #Agility# #Potential#",
"Sandman00 character sandman" : "Sandman [Classic] #Super Villain# #Villain# #Combat# #Male# #Human# #Sinister Six# #Durability#",
"Satana00 character satana" : "Satana [Modern] #Super Hero# #Hero# #Universal# #Female# #Human# #Flame# #Magic#",
"Satana01 uniform satana1" : "Satana [Marvel Legacy] #Super Hero# #Hero# #Universal# #Female# #Human# #Flame# #Magic#",
"ScarletWitch00 character scarletwitch" : "Scarlet Witch [Classic] #Super Hero# #Hero# #Blast# #Female# #Other# #Fast Movement# #Chaos Magic# #Potential#",
"ScarletWitch01 uniform scarletwitch1" : "Scarlet Witch [Marvel's Avengers: Infinity War] #Super Hero# #Hero# #Blast# #Female# #Other# #MCU# #Avengers# #Fast Movement# #Chaos Magic# #Potential#",
"Sentinel00 character sentinel" : "Sentinel [Modern] #Super Villain# #Villain# #Universal# #Neutral# #Creature# #Pure Evil# #Machine# #Potential#",
"ShangChi00 character shang" : "Shang Chi [Modern] #Super Hero# #Hero# #Combat# #Male# #Human# #Leadership# #Agility#",
"SheHulk00 character shulk" : "She-Hulk [Secret Wars: A-Force] #Super Hero# #Hero# #Combat# #Female# #Human# #Durability# #Strong# #Potential#",
"SheHulk01 uniform shulk1" : "She-Hulk [All-New] #Super Hero# #Hero# #Combat# #Female# #Human# #Durability# #Strong# #Potential#",
"SheHulk02 uniform shulk2" : "She-Hulk [Fantastic Four] #Super Hero# #Hero# #Combat# #Female# #Human# #Fantastic Four# #Durability# #Strong# #Potential#",
"Shuri00 character shuri" : "Shuri [Marvel Legacy] #Super Hero# #Hero# #Speed# #Female# #Human# #Leadership# #Heightened Senses# #Support#",
"Shuri01 uniform shuri1" : "Shuri [Marvel's Black Panther] #Super Hero# #Hero# #Speed# #Female# #Human# #MCU# #Leadership# #Heightened Senses# #Support#",
"Sif00 character sif" : "Sif [Marvel's Agents of S.H.I.E.L.D.] #Super Hero# #Hero# #Combat# #Female# #Alien# #Shield# #Asgard# #Agility#",
"Sif01 uniform sif1" : "Sif [Modern] #Super Hero# #Hero# #Combat# #Female# #Alien# #Asgard# #Agility#",
"Silk00 character silk" : "Silk [All-New, All-Different] #Super Hero# #Hero# #Speed# #Female# #Human# #Spidey# #Agility# #Spider-Sense#",
"Silk01 uniform silk1" : "Silk [Web Suit] #Super Hero# #Hero# #Speed# #Female# #Human# #Spidey# #Agility# #Spider-Sense#",
"Sin00 character sin" : "Sin [All-New, All-Different] #Super Villain# #Villain# #Speed# #Female# #Human# #Pure Evil# #Weapons Master# #Support#",
"Singularity00 character singularity" : "Singularity [Secret Wars: A-Force] #Super Hero# #Hero# #Universal# #Female# #Alien# #Energy Projection# #Fast Movement#",
"SisterGrimm00 character grimm" : "Sister Grimm [Secret Wars: A-Force] #Super Hero# #Hero# #Blast# #Female# #Human# #Magic#",
"SisterGrimm01 uniform grimm1" : "Sister Grimm [All-New, All-Different] #Super Hero# #Hero# #Blast# #Female# #Human# #Magic#",
"Skurge00 character skurge" : "Skurge [Marvel's Thor: Ragnarok] #Super Villain# #Villain# #Combat# #Male# #Alien# #MCU# #Asgard# #Durability# #Strong#",
"Songbird00 character songbird" : "Songbird [New Avengers] #Super Hero# #Hero# #Blast# #Female# #Human# #Agent# #Fast Movement#",
"SpiderGwen00 character gwen" : "Spider-Gwen [All-New, All-Different] #Super Hero# #Hero# #Speed# #Female# #Human# #Spidey# #Leadership# #Agility# #Spider-Sense#",
"SpiderGwen01 uniform gwen1" : "Spider-Gwen [Gwendolyne Stacy] #Super Hero# #Hero# #Speed# #Female# #Human# #Spidey# #Leadership# #Agility# #Spider-Sense#",
"SpiderMan00 character spidey" : "Spider-Man [Classic] #Super Hero# #Hero# #Speed# #Male# #Human# #Spidey# #Agility# #Leadership# #Spider-Sense# #Potential# #Tier3#",
"SpiderMan01 uniform spidey1" : "Spider-Man [Secret Wars: Renew Your Vows] #Super Hero# #Hero# #Speed# #Male# #Human# #Spidey# #Agility# #Leadership# #Spider-Sense# #Potential# #Tier3#",
"SpiderMan02 uniform spidey2" : "Spider-Man [All-New, All-Different] #Super Hero# #Hero# #Speed# #Male# #Human# #Spidey# #Agility# #Leadership# #Spider-Sense# #Potential# #Tier3#",
"SpiderMan03 uniform spidey3" : "Spider-Man [Captain America: Civil War] #Super Hero# #Hero# #Speed# #Male# #Human# #MCU# #Spidey# #Agility# #Leadership# #Spider-Sense# #Potential# #Tier3#",
"SpiderMan04 uniform spidey4" : "Spider-Man [Spider-Man: Homecoming Homemade Suit] #Super Hero# #Hero# #Speed# #Male# #Human# #MCU# #Spidey# #Agility# #Leadership# #Spider-Sense# #Potential# #Tier3#",
"SpiderMan05 uniform spidey5" : "Spider-Man [Marvel's Avengers: Infinity War] #Super Hero# #Hero# #Speed# #Male# #Human# #MCU# #Spidey# #-# #Avengers# #Agility# #Leadership# #Spider-Sense# #Potential# #Tier3#",
"SpiderMan209900 character spidey2099" : "Spider-Man 2099 [Modern] #Super Hero# #Hero# #Speed# #Male# #Human# #Spidey# #Agility# #Leadership# #Spider-Sense#",
"SpiderManMilesMorales00 character miles" : "Spider-Man (Miles Morales) [All-New, All-Different] #Super Hero# #Hero# #Speed# #Male# #Human# #Spidey# #Leadership# #Agility# #Spider-Sense# #Potential#",
"SpiderManMilesMorales01 uniform miles1" : "Spider-Man (Miles Morales) [Into The Spider-Verse] #Super Hero# #Hero# #Speed# #Male# #Human# #Spidey# #Leadership# #Agility# #Spider-Sense# #Potential#",
"SquirrelGirl00 character squirrel" : "Squirrel Girl [New Avengers] #Super Hero# #Hero# #Speed# #Female# #Human# #Agility#",
"SquirrelGirl01 uniform squirrel1" : "Squirrel Girl [Marvel NOW!] #Super Hero# #Hero# #Speed# #Female# #Human# #Agility#",
"StarLord00 character star" : "Star-Lord [Guardians of the Galaxy] #Super Hero# #Hero# #Blast# #Male# #Alien# #MCU# #Guardians# #Command# #Weapons Master# #Potential#",
"StarLord01 uniform star1" : "Star-Lord [Space Armor] #Super Hero# #Hero# #Blast# #Male# #Alien# #Guardians# #Command# #Weapons Master# #Potential#",
"StarLord02 uniform star2" : "Star-Lord [Guardians of the Galaxy 2] #Super Hero# #Hero# #Blast# #Male# #Alien# #MCU# #Guardians# #Command# #Weapons Master# #Potential#",
"StarLord03 uniform star3" : "Star-Lord [Marvel's Avengers: Infinity War] #Super Hero# #Hero# #Blast# #Male# #Alien# #MCU# #Avengers# #-# #Guardians# #Command# #Weapons Master# #Potential#",
"Storm00 character storm" : "Storm [Modern] #Super Hero# #Hero# #Blast# #Female# #Mutant# #X-Men# #Command# #Shock# #Support#",
"Stryfe00 character stryfe" : "Stryfe [Modern] #Super Villain# #Villain# #Blast# #Male# #Mutant# #Energy Projection# #Pure Evil# #Potential#",
"Supergiant00 character supergiant" : "Supergiant [Infinity] #Super Villain# #Villain# #Universal# #Female# #Alien# #Black Order# #Mind Resist# #Mind#",
"Surtur00 character surtur" : "Surtur [Surtur] #Super Villain# #Villain# #Male# #Alien# #Asgard# #NPC#",
"Talos00 character talos" : "Talos [Captain Marvel] #Super Villain# #Villain# #Male# #Alien# #MCU# #Skrull# #NPC#",
"Thanos00 character thanos" : "Thanos [Infinity] #Super Villain# #Villain# #Universal# #Male# #Alien# #Pure Evil# #Durability# #Strong# #Potential# #Tier3#",
"Thanos01 uniform thanos1" : "Thanos [Secret Wars: Infinity] #Super Villain# #Villain# #Universal# #Male# #Alien# #Pure Evil# #Durability# #Strong# #Potential# #Tier3#",
"Thanos02 uniform thanos2" : "Thanos [Marvel's Avengers: Infinity War] #Super Villain# #Villain# #Universal# #Male# #Alien# #MCU# #Pure Evil# #Durability# #Strong# #Potential# #Tier3#",
"Thanos03 uniform thanos3" : "Thanos [Marvel's Avengers: Endgame] #Super Villain# #Villain# #Universal# #Male# #Alien# #MCU# #Pure Evil# #Durability# #Strong# #Potential# #Tier3# #New#",
"Thing00 character thing" : "Thing [Modern] #Super Hero# #Hero# #Combat# #Male# #Human# #Fantastic Four# #Durability# #Strong# #Support# #Potential#",
"Thor00 character thor" : "Thor [The Avengers] #Super Hero# #Hero# #Universal# #Male# #Alien# #MCU# #Avengers# #-# #Asgard# #Leadership# #Shock# #Potential# #Tier3#",
"Thor01 uniform thor1" : "Thor [Avengers: Age of Ultron] #Super Hero# #Hero# #Universal# #Male# #Alien# #MCU# #Avengers# #-# #Asgard# #Leadership# #Shock# #Potential# #Tier3#",
"Thor02 uniform thor2" : "Thor [Unworthy] #Super Hero# #Hero# #Universal# #Male# #Alien# #Asgard# #Leadership# #Shock# #Potential# #Tier3#",
"Thor03 uniform thor3" : "Thor [Marvel's Thor: Ragnarok] #Super Hero# #Hero# #Universal# #Male# #Alien# #MCU# #Avengers# #-# #Asgard# #Leadership# #Shock# #Potential# #Tier3#",
"Thor04 uniform thor4" : "Thor [Marvel's Avengers: Infinity War] #Super Hero# #Hero# #Universal# #Male# #Alien# #MCU# #Avengers# #-# #Asgard# #Leadership# #Shock# #Potential# #Tier3#",
"ThorJaneFoster00 character jane" : "Thor (Jane Foster) [All-New, All-Different] #Super Hero# #Hero# #Universal# #Female# #Alien# #Asgard# #Fast Movement# #Shock#",
"Titania00 character titania" : "Titania [Modern] #Super Villain# #Villain# #Combat# #Female# #Human# #Strong#",
"Ulik00 character ulik" : "Ulik [Modern] #Super Villain# #Villain# #Combat# #Male# #Alien# #Asgard# #Durability# #Strong#",
"Ultron00 character ultron" : "Ultron [Modern] #Super Villain# #Villain# #Universal# #Male# #Creature# #Pure Evil# #Machine#",
"Ultron01 uniform ultron1" : "Ultron Prime [Avengers: Age of Ultron] #Super Villain# #Villain# #Universal# #Male# #Creature# #MCU# #Pure Evil# #Machine#",
"Ultron02 uniform ultron2" : "Ultron Mark 1 [Avengers: Age of Ultron] #Super Villain# #Villain# #Universal# #Male# #Creature# #MCU# #Pure Evil# #Machine#",
"Ultron03 uniform ultron3" : "Ultron Mark 3 [Avengers: Age of Ultron] #Super Villain# #Villain# #Universal# #Male# #Creature# #MCU# #Pure Evil# #Machine#",
"UlyssesKlaue00 character klaue" : "Ulysses Klaue [Marvel's Black Panther] #Super Villain# #Villain# #Blast# #Male# #Human# #MCU# #Weapons Master# #Support#",
"Valkyrie00 character valkyrie" : "Valkyrie [Marvel's Thor: Ragnarok] #Super Hero# #Hero# #Combat# #Female# #Alien# #MCU# #Asgard# #Strong# #Support#",
"Venom00 character venom" : "Venom [Classic] #Super Villain# #Villain# #Combat# #Male# #Human# #Symbiote# #Healing#",
"Venom01 uniform venom1" : "Venom [Secret Wars: Marvel Zombies] #Super Villain# #Villain# #Combat# #Male# #Human# #Symbiote# #Healing#",
"Venom02 uniform venom2" : "Venom [Anti-Venom] #Super Hero# #Hero# #Combat# #Male# #Human# #Symbiote# #Healing# #Support#",
"Victorious00 character victorious" : "Victorious [Modern] #Super Villain# #Villain# #Universal# #Female# #Human# #Energy Projection# #Fast Movement# #Support# #Potential#",
"Vision00 character vision" : "Vision [Modern] #Super Hero# #Hero# #Blast# #Male# #Creature# #Durability# #Fast Movement# #Machine#",
"Vision01 uniform vision1" : "Vision [Avengers: Age of Ultron] #Super Hero# #Hero# #Universal# #Male# #Creature# #MCU# #Avengers# #Durability# #Fast Movement# #Machine#",
"Volstagg00 character volstagg" : "Volstagg [Modern] #Super Hero# #Hero# #Combat# #Male# #Alien# #Asgard# #Durability# #Support#",
"Vulture00 character vulture" : "Vulture [Classic] #Super Villain# #Villain# #Speed# #Male# #Human# #Sinister Six# #Agility# #Fast Movement#",
"Vulture01 uniform vulture1" : "Vulture [Spider-Man: Homecoming] #Super Villain# #Villain# #Speed# #Male# #Human# #MCU# #Sinister Six# #Agility# #Fast Movement#",
"WarMachine00 character wm" : "War Machine [Modern] #Super Hero# #Hero# #Blast# #Male# #Human# #Avengers# #Leadership# #Machine# #Potential#",
"WarMachine01 uniform wm1" : "War Machine [Iron Patriot] #Super Hero# #Hero# #Blast# #Male# #Human# #Avengers# #Leadership# #Machine# #Potential#",
"WarMachine02 uniform wm2" : "War Machine [Avengers: The Initiative] #Super Hero# #Hero# #Blast# #Male# #Human# #Avengers# #Leadership# #Machine# #Potential#",
"WarMachine03 uniform wm3" : "War Machine [Captain America: Civil War] #Super Hero# #Hero# #Blast# #Male# #Human# #MCU# #Avengers# #Leadership# #Machine# #Potential#",
"WarMachine04 uniform wm4" : "War Machine [Marvel's Avengers: Infinity War] #Super Hero# #Hero# #Blast# #Male# #Human# #MCU# #Avengers# #Leadership# #Machine# #Potential#",
"WarMachine05 uniform wm5" : "War Machine [Marvel's Avengers: Endgame] #Super Hero# #Hero# #Blast# #Male# #Human# #MCU# #Avengers# #Leadership# #Machine# #Potential# #New#",
"WarMachine06 uniform wm6" : "War Machine [Team Suit] #Super Hero# #Hero# #Blast# #Male# #Human# #MCU# #Avengers# #Leadership# #Machine# #Potential# #New#",
"Warpath00 character warpath" : "Warpath [X-Force] #Super Hero# #Hero# #Combat# #Male# #Mutant# #X-Force# #Leadership# #Strong# #Potential#",
"Warwolf00 character warwolf" : "Warwolf [The Howling Commandos of S.H.I.E.L.D.] #Super Hero# #Hero# #Combat# #Male# #Human# #Shield# #Agent# #Healing# #Support#",
"Wasp00 character wasp" : "Wasp [Modern] #Super Hero# #Hero# #Blast# #Female# #Human# #Fast Movement# #Support# #Potential#",
"Wasp01 uniform wasp1" : "Wasp [All-New, All-Different] #Super Hero# #Hero# #Blast# #Female# #Human# #Fast Movement# #Support# #Potential#",
"Wasp02 uniform wasp2" : "Wasp [Marvel's Ant-Man and the Wasp] #Super Hero# #Hero# #Blast# #Female# #Human# #MCU# #Fast Movement# #Support# #Potential#",
"WaspNadia VanDyne00 character nadiavan" : "Wasp (Nadia Van Dyne) [Modern] #Super Hero# #Hero# #Blast# #Female# #Human# #Agent# #Fast Movement# #Support#",
"WeaponHex00 character weaponhex" : "Weapon Hex [Infinity Warps] #Super Hero# #Hero# #Blast# #Female# #Mutant# #Chaos Magic# #Healing# #Agility# #Support# #Potential#",
"Whiplash00 character whiplash" : "Whiplash [Marvel's Iron Man 2] #Super Villain# #Villain# #Blast# #Male# #Human# #MCU# #Machine# #Shock#",
"WhiteFox00 character whitefox" : "White Fox [Modern] #Super Hero# #Hero# #Speed# #Female# #Human# #Leadership# #Agility# #Support# #Potential#",
"WhiteTiger00 character tiger" : "White Tiger [New Avengers] #Super Hero# #Hero# #Combat# #Female# #Human# #Agility#",
"Wiccan00 character wiccan" : "Wiccan [New Avengers] #Super Hero# #Hero# #Blast# #Male# #Human# #Energy Projection# #Fast Movement# #Support#",
"WinterSoldier00 character bucky" : "Winter Soldier [Captain America: The Winter Soldier] #Super Hero# #Hero# #Speed# #Male# #Human# #MCU# #Weapons Master# #Support# #Potential#",
"WinterSoldier01 uniform bucky1" : "Winter Soldier [Captain America: Civil War] #Super Hero# #Hero# #Speed# #Male# #Human# #MCU# #Weapons Master# #Support# #Potential#",
"WinterSoldier02 uniform bucky2" : "Winter Soldier [Captain America] #Super Hero# #Hero# #Speed# #Male# #Human# #Weapons Master# #Support# #Potential#",
"WinterSoldier03 uniform bucky3" : "Winter Soldier [Marvel's Avengers: Infinity War] #Super Hero# #Hero# #Speed# #Male# #Human# #MCU# #Avengers# #Weapons Master# #Support# #Potential#",
"Wolverine00 character wolverine" : "Wolverine [Classic] #Super Hero# #Hero# #Combat# #Male# #Mutant# #X-Men# #Healing# #Weapons Master#",
"Wolverine01 uniform wolverine1" : "Wolverine [Age of Apocalypse] #Super Hero# #Hero# #Combat# #Male# #Mutant# #X-Men# #Healing# #Weapons Master#",
"Wolverine02 uniform wolverine2" : "Wolverine [All-New Marvel NOW!] #Super Hero# #Hero# #Combat# #Male# #Mutant# #X-Men# #Healing# #Weapons Master#",
"Wolverine03 uniform wolverine3" : "Wolverine [X-Force] #Super Hero# #Hero# #Combat# #Male# #Mutant# #X-Force# #Healing# #Weapons Master# #Potential# #Tier3#",
"Wong00 character wong" : "Wong [All-New, All-Different] #Super Hero# #Hero# #Speed# #Male# #Human# #Weapons Master#",
"Wong01 uniform wong1" : "Wong [Marvel's Doctor Strange] #Super Hero# #Hero# #Speed# #Male# #Human# #MCU# #Weapons Master#",
"X2300 character laura" : "X-23 [Classic] #Super Hero# #Hero# #Speed# #Female# #Mutant# #X-Men# #Healing# #Agility# #Potential#",
"X2301 uniform laura1" : "X-23 [X-Force] #Super Hero# #Hero# #Speed# #Female# #Mutant# #X-Force# #Healing# #Agility# #Potential#",
"Yellowjacket00 character yj" : "Yellowjacket [Marvel's Ant-Man] #Super Villain# #Villain# #Blast# #Male# #Human# #MCU# #Machine# #Pure Evil#",
"Yellowjacket01 uniform yj1" : "Yellowjacket [Marvel NOW!] #Super Villain# #Villain# #Blast# #Male# #Human# #Machine# #Pure Evil#",
"Ymir00 character ymir" : "Ymir [Ymir] #Super Villain# #Villain# #Male# #Alien# #Asgard# #NPC#",
"Yondu00 character yondu" : "Yondu [Guardians of the Galaxy] #Super Hero# #Hero# #Speed# #Male# #Alien# #MCU# #Guardians# #Weapons Master# #Command#",
"Yondu01 uniform yondu1" : "Yondu [All-New, All-Different] #Super Hero# #Hero# #Speed# #Male# #Alien# #Weapons Master# #Command#",
"Yondu02 uniform yondu2" : "Yondu [Guardians of the Galaxy 2] #Super Hero# #Hero# #Speed# #Male# #Alien# #MCU# #Guardians# #Weapons Master# #Command#",






};
